/**
 * Realistic Myanmar Business Seed Data
 * Provides an authentic operational database with rooms, services, staff, products, and default accounts.
 */

import { db } from './database';
import { hashPin } from '../utils/cryptoAuth';
import {
  UserAccount,
  Room,
  StaffMember,
  ServiceItem,
  ProductItem,
  Customer,
  ShopSettings,
  StaffLedgerEntry,
  ExpenseRecord,
  StaffType,
  TableRecord,
  ServiceCategory,
  ProductCategory,
  PaymentMethodRecord,
  ExpenseCategoryRecord,
  CommissionRuleRecord,
} from '../types';

let seedPromise: Promise<void> | null = null;

export function seedDatabaseIfEmpty(): Promise<void> {
  if (!seedPromise) {
    seedPromise = internalSeedDatabaseIfEmpty().finally(() => {
      seedPromise = null;
    });
  }
  return seedPromise;
}

async function internalSeedDatabaseIfEmpty(): Promise<void> {
  const [roomCount, userCount, settingsCount, staffTypeCount] = await Promise.all([
    db.rooms.count(),
    db.users.count(),
    db.settings.count(),
    db.staffTypes.count(),
  ]);

  // If already seeded across core collections, check and fill any empty master tables
  if (roomCount > 0 && userCount > 0 && settingsCount > 0 && staffTypeCount > 0) return;

  console.log('Seeding initial Myanmar Business ERP database...');

  const now = new Date().toISOString();

  // 1. Settings
  const defaultSettings: ShopSettings = {
    id: 'settings_main',
    shopName: 'Shwe Thiri Spa & KTV Lounge',
    shopNameMm: 'ရွှေသီရိ အကြောပြင်၊ စပါနှင့် ကာရာအိုကေ',
    phone: '09-798881234 / 09-450009876',
    address: 'No. 45, Kabar Aye Pagoda Road, Bahan Township, Yangon',
    addressMm: 'အမှတ် (၄၅)၊ ကမ္ဘာအေးဘုရားလမ်း၊ ဗဟန်းမြို့နယ်၊ ရန်ကုန်မြို့။',
    taxPercent: 0, // In Myanmar, small shops often don't charge commercial tax unless requested
    serviceChargePercent: 0,
    allowNegativeStock: false,
    requirePinForVoid: true,
    receiptFooterNote: 'Thank you for choosing Shwe Thiri. Please visit us again!',
    receiptFooterNoteMm: 'ရွှေသီရိကို ရွေးချယ်အားပေးသည့်အတွက် အထူးကျေးဇူးတင်ရှိပါသည်။ နောက်တစ်ကြိမ် ထပ်မံကြွရောက်ပါရန် လှိုက်လှဲစွာ ဖိတ်ခေါ်အပ်ပါသည်။',
    currencySymbol: 'MMK',
  };

  // 2. Users (Salted SHA-256 PIN Hashes)
  const ownerHash = hashPin('1234', 'salt_owner_init');
  const managerHash = hashPin('5678', 'salt_manager_init');
  const cashierHash = hashPin('0000', 'salt_cashier_init');

  const defaultUsers: UserAccount[] = [
    {
      id: 'usr_owner',
      name: 'U Zaw Min (ဦးဇော်မင်း - ဆိုင်ရှင်)',
      username: 'owner',
      pinHash: ownerHash.pinHash,
      pinSalt: ownerHash.pinSalt,
      role: 'owner',
      isActive: true,
      createdAt: now,
    },
    {
      id: 'usr_manager',
      name: 'Daw Sandar (ဒေါ်စန္ဒာ - မန်နေဂျာ)',
      username: 'manager',
      pinHash: managerHash.pinHash,
      pinSalt: managerHash.pinSalt,
      role: 'manager',
      isActive: true,
      createdAt: now,
    },
    {
      id: 'usr_cashier',
      name: 'Maung Kyaw (မောင်ကျော် - ငွေကိုင်)',
      username: 'cashier',
      pinHash: cashierHash.pinHash,
      pinSalt: cashierHash.pinSalt,
      role: 'cashier',
      isActive: true,
      createdAt: now,
    },
  ];

  // 3. Rooms
  const defaultRooms: Room[] = [
    {
      id: 'rm_vip1',
      name: 'VIP Suite 1 (Rose)',
      nameMm: 'နှင်းဆီ (VIP အခန်း ၁)',
      roomNumber: 'VIP-01',
      type: 'vip_suite',
      hourlyRateMMK: 25000,
      surchargeMMK: 10000,
      basePriceMMK: 25000,
      status: 'available',
      capacity: 2,
      isActive: true,
      maintenanceNotes: '',
    },
    {
      id: 'rm_vip2',
      name: 'VIP Suite 2 (Padauk)',
      nameMm: 'ပိတောက် (VIP အခန်း ၂)',
      roomNumber: 'VIP-02',
      type: 'vip_suite',
      hourlyRateMMK: 25000,
      surchargeMMK: 10000,
      basePriceMMK: 25000,
      status: 'available',
      capacity: 2,
      isActive: true,
      maintenanceNotes: '',
    },
    {
      id: 'rm_std1',
      name: 'Massage Room A (Thabye)',
      nameMm: 'သပြေ (ရိုးရာနှိပ်ခန်း A)',
      roomNumber: 'STD-01',
      type: 'massage_bed',
      hourlyRateMMK: 0,
      surchargeMMK: 0,
      basePriceMMK: 0,
      status: 'available',
      capacity: 1,
      isActive: true,
      maintenanceNotes: '',
    },
    {
      id: 'rm_std2',
      name: 'Massage Room B (Jasmine)',
      nameMm: 'စံပယ် (ရိုးရာနှိပ်ခန်း B)',
      roomNumber: 'STD-02',
      type: 'massage_bed',
      hourlyRateMMK: 0,
      surchargeMMK: 0,
      basePriceMMK: 0,
      status: 'available',
      capacity: 1,
      isActive: true,
      maintenanceNotes: '',
    },
    {
      id: 'rm_foot1',
      name: 'Foot Reflexology Lounge (Chair 1-4)',
      nameMm: 'ခြေဖဝါးအကြောပြင်ခန်းမ (ထိုင်ခုံ ၁-၄)',
      roomNumber: 'FT-01',
      type: 'foot_hall',
      hourlyRateMMK: 0,
      surchargeMMK: 0,
      basePriceMMK: 0,
      status: 'available',
      capacity: 4,
      isActive: true,
      maintenanceNotes: '',
    },
    {
      id: 'rm_ktv1',
      name: 'VIP KTV 1 (Golden Moon)',
      nameMm: 'ရွှေလမင်း (VIP ကာရာအိုကေ)',
      roomNumber: 'KTV-01',
      type: 'ktv_large',
      hourlyRateMMK: 35000,
      surchargeMMK: 5000,
      basePriceMMK: 35000,
      status: 'available',
      capacity: 10,
      isActive: true,
      maintenanceNotes: '',
    },
    {
      id: 'rm_ktv2',
      name: 'KTV 2 (Silver Star)',
      nameMm: 'ငွေကြယ်စင် (ကာရာအိုကေ)',
      roomNumber: 'KTV-02',
      type: 'ktv_medium',
      hourlyRateMMK: 25000,
      surchargeMMK: 0,
      basePriceMMK: 25000,
      status: 'available',
      capacity: 6,
      isActive: true,
      maintenanceNotes: '',
    },
  ];

  // 3b. Dining Tables
  const defaultTables: TableRecord[] = [
    {
      id: 'tbl_1',
      tableNumber: 'T-01',
      name: 'Dining Table 1',
      nameMm: 'စားပွဲ ၁ (ဧည့်ခန်းမ)',
      capacity: 4,
      status: 'available',
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'tbl_2',
      tableNumber: 'T-02',
      name: 'Dining Table 2',
      nameMm: 'စားပွဲ ၂ (ဧည့်ခန်းမ)',
      capacity: 4,
      status: 'available',
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'tbl_3',
      tableNumber: 'T-03',
      name: 'Dining Table 3',
      nameMm: 'စားပွဲ ၃ (ဝရန်တာ)',
      capacity: 6,
      status: 'available',
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'tbl_4',
      tableNumber: 'T-04',
      name: 'Dining Table 4',
      nameMm: 'စားပွဲ ၄ (အပြင်ဘက်)',
      capacity: 6,
      status: 'available',
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'tbl_5',
      tableNumber: 'T-05',
      name: 'VIP Lounge Table 5',
      nameMm: 'စားပွဲ ၅ (VIP သီးသန့်)',
      roomId: 'rm_vip1',
      capacity: 8,
      status: 'available',
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
  ];

  // 4. Staff Types
  const defaultStaffTypes: StaffType[] = [
    {
      id: 'stype_senior',
      code: 'ST-SR-THERAPIST',
      name: 'Senior Therapist',
      nameMm: 'ဝါရင့် အကြောပြင်ပညာရှင်',
      description: 'Experienced specialist with over 3 years clinical massage background',
      defaultCommissionType: 'percentage',
      defaultCommissionValue: 40,
      baseSalaryMMK: 350000,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'stype_therapist',
      code: 'ST-THERAPIST',
      name: 'Massage Therapist',
      nameMm: 'အကြောပြင်ကျွမ်းကျင်',
      description: 'Standard traditional & oil massage practitioner',
      defaultCommissionType: 'percentage',
      defaultCommissionValue: 35,
      baseSalaryMMK: 250000,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'stype_masseuse',
      code: 'ST-MASSEUSE',
      name: 'Traditional Masseuse',
      nameMm: 'ရိုးရာနှိပ်နယ်သူ',
      description: 'Traditional Myanmar herbal massage and reflexology specialist',
      defaultCommissionType: 'percentage',
      defaultCommissionValue: 30,
      baseSalaryMMK: 200000,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'stype_waiter',
      code: 'ST-WAITER',
      name: 'Waiter',
      nameMm: 'စားပွဲထိုး ဝန်ထမ်း',
      description: 'Food and beverage server for rooms and lounge dining',
      defaultCommissionType: 'percentage',
      defaultCommissionValue: 20,
      baseSalaryMMK: 200000,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'stype_ktv_host',
      code: 'ST-KTV-HOST',
      name: 'KTV Lounge Host',
      nameMm: 'ကာရာအိုကေ ဧည့်ကြိုနှင့် ဝန်ဆောင်မှု',
      description: 'Customer assistance, entertainment and beverage service in KTV suites',
      defaultCommissionType: 'percentage',
      defaultCommissionValue: 40,
      baseSalaryMMK: 220000,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'stype_reception',
      code: 'ST-RECEPTION',
      name: 'Reception Staff',
      nameMm: 'ဧည့်ကြို ဝန်ထမ်း',
      description: 'Guest greeting, booking management and front desk receptionist',
      defaultCommissionType: 'fixed',
      defaultCommissionValue: 0,
      baseSalaryMMK: 280000,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
  ];

  // 4b. Staff Members
  const defaultStaff: StaffMember[] = [
    {
      id: 'stf_1',
      name: 'Ma Hnin Nu',
      nameMm: 'မနှင်းနု',
      phone: '09-421112233',
      address: 'Bahan Township, Yangon',
      role: 'therapist',
      staffTypeId: 'stype_senior',
      status: 'available',
      defaultCommissionRule: { type: 'percentage', value: 35, ruleId: 'crule_pct35', version: 1 },
      commissionRuleId: 'crule_pct35',
      baseSalaryMMK: 350000,
      isActive: true,
      joinedDate: '2025-01-10',
      notes: 'Lead therapist, high customer retention',
    },
    {
      id: 'stf_2',
      name: 'Ma Aye Thandar',
      nameMm: 'မအေးသန္တာ',
      phone: '09-425556677',
      address: 'Sanchaung Township, Yangon',
      role: 'therapist',
      staffTypeId: 'stype_therapist',
      status: 'available',
      defaultCommissionRule: { type: 'percentage', value: 35, ruleId: 'crule_pct35', version: 1 },
      commissionRuleId: 'crule_pct35',
      baseSalaryMMK: 250000,
      isActive: true,
      joinedDate: '2025-02-15',
      notes: 'Specializes in aromatherapy and reflexology',
    },
    {
      id: 'stf_3',
      name: 'Ko Than Naing',
      nameMm: 'ကိုသန်းနိုင်',
      phone: '09-250001122',
      address: 'Kamayut Township, Yangon',
      role: 'therapist',
      staffTypeId: 'stype_therapist',
      status: 'available',
      defaultCommissionRule: { type: 'fixed', value: 7000, ruleId: 'crule_fixed7000', version: 1 },
      commissionRuleId: 'crule_fixed7000',
      baseSalaryMMK: 250000,
      isActive: true,
      joinedDate: '2024-11-01',
      notes: 'Expert in traditional herbal acupressure',
    },
    {
      id: 'stf_4',
      name: 'Daw Khin Win',
      nameMm: 'ဒေါ်ခင်ဝင်း',
      phone: '09-778899001',
      address: 'Hlaing Township, Yangon',
      role: 'masseuse',
      staffTypeId: 'stype_masseuse',
      status: 'available',
      defaultCommissionRule: { type: 'percentage', value: 30, version: 1 },
      baseSalaryMMK: 200000,
      isActive: true,
      joinedDate: '2024-08-20',
      notes: 'Traditional body work',
    },
    {
      id: 'stf_5',
      name: 'Ma Su Myat',
      nameMm: 'မဆုမြတ်',
      phone: '09-976543210',
      address: 'Yankin Township, Yangon',
      role: 'ktv_host',
      staffTypeId: 'stype_ktv_host',
      status: 'available',
      defaultCommissionRule: { type: 'percentage', value: 40, version: 1 },
      baseSalaryMMK: 220000,
      isActive: true,
      joinedDate: '2025-03-01',
      notes: 'KTV host and lounge coordinator',
    },
    {
      id: 'stf_6',
      name: 'Ko Kyaw Zaya',
      nameMm: 'ကိုကျော်ဇေယျ',
      phone: '09-887766554',
      address: 'Bahan Township, Yangon',
      role: 'waiter',
      staffTypeId: 'stype_waiter',
      status: 'available',
      defaultCommissionRule: { type: 'percentage', value: 20, version: 1 },
      baseSalaryMMK: 200000,
      isActive: true,
      joinedDate: '2025-01-15',
      notes: 'Waiter and beverage service staff',
    },
    {
      id: 'stf_7',
      name: 'Ma Chit Su',
      nameMm: 'မချစ်စု',
      phone: '09-112233445',
      address: 'Tamwe Township, Yangon',
      role: 'receptionist',
      staffTypeId: 'stype_reception',
      status: 'available',
      defaultCommissionRule: { type: 'fixed', value: 0, version: 1 },
      baseSalaryMMK: 280000,
      isActive: true,
      joinedDate: '2024-10-01',
      notes: 'Front desk reception staff',
    },
  ];

  // 5a. Service Categories
  const defaultServiceCategories: ServiceCategory[] = [
    {
      id: 'scat_massage',
      code: 'SC-MASSAGE',
      name: 'Traditional Massage',
      nameMm: 'မြန်မာ့ရိုးရာ အကြောပြင်',
      description: 'Authentic body and pressure point relief therapies',
      sortOrder: 1,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'scat_spa',
      code: 'SC-SPA',
      name: 'Aromatherapy & Spa',
      nameMm: 'ဆီမွှေးနှင့် စပါ',
      description: 'Natural herbal oil and deep tissue relaxation',
      sortOrder: 2,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'scat_foot',
      code: 'SC-FOOT',
      name: 'Foot Reflexology',
      nameMm: 'ခြေဖဝါးအကြောပြင်',
      description: 'Acupressure foot soak and meridian stimulation',
      sortOrder: 3,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'scat_facial',
      code: 'SC-FACIAL',
      name: 'Facial Treatment',
      nameMm: 'မျက်နှာပေါင်းတင် အလှပြုပြင်',
      description: 'Skin cleansing, herbal scrub and rejuvenation mask',
      sortOrder: 4,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'scat_ktv',
      code: 'SC-KTV',
      name: 'KTV Lounge & Karaoke',
      nameMm: 'ကာရာအိုကေ သီးသန့်အခန်း',
      description: 'High-end sound system room entertainment',
      sortOrder: 5,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
  ];

  // 5b. Services Catalog
  const defaultServices: ServiceItem[] = [
    {
      id: 'srv_1',
      name: 'Myanmar Traditional Body Massage (60 mins)',
      nameMm: 'မြန်မာ့ရိုးရာ တိုင်းရင်းဆေးပေါင်းဆီနှိပ်နယ်ခြင်း (၆၀ မိနစ်)',
      category: 'massage',
      categoryId: 'scat_massage',
      pricingMethod: 'duration_based',
      durationMinutes: 60,
      priceMMK: 30000,
      defaultCommissionRule: { type: 'percentage', value: 35, ruleId: 'crule_pct35', version: 1 },
      commissionRuleId: 'crule_pct35',
      isActive: true,
    },
    {
      id: 'srv_2',
      name: 'Myanmar Traditional Body Massage (90 mins)',
      nameMm: 'မြန်မာ့ရိုးရာ တိုင်းရင်းဆေးပေါင်းဆီနှိပ်နယ်ခြင်း (၉၀ မိနစ်)',
      category: 'massage',
      categoryId: 'scat_massage',
      pricingMethod: 'duration_based',
      durationMinutes: 90,
      priceMMK: 42000,
      defaultCommissionRule: { type: 'percentage', value: 35, ruleId: 'crule_pct35', version: 1 },
      commissionRuleId: 'crule_pct35',
      isActive: true,
    },
    {
      id: 'srv_3',
      name: 'Thai Aromatherapy Oil Relaxation (60 mins)',
      nameMm: 'ထိုင်းရနံ့ဆီ အကြောလျှော့နှိပ်နယ်ခြင်း (၆၀ မိနစ်)',
      category: 'spa',
      categoryId: 'scat_spa',
      pricingMethod: 'duration_based',
      durationMinutes: 60,
      priceMMK: 38000,
      defaultCommissionRule: { type: 'percentage', value: 40, ruleId: 'crule_pct40', version: 1 },
      commissionRuleId: 'crule_pct40',
      isActive: true,
    },
    {
      id: 'srv_4',
      name: 'Foot Reflexology & Herbal Soak (60 mins)',
      nameMm: 'တိုင်းရင်းဆေးစိမ် ခြေဖဝါးအကြောပြင် (၆၀ မိနစ်)',
      category: 'foot',
      categoryId: 'scat_foot',
      pricingMethod: 'duration_based',
      durationMinutes: 60,
      priceMMK: 22000,
      defaultCommissionRule: { type: 'percentage', value: 30, version: 1 },
      isActive: true,
    },
    {
      id: 'srv_5',
      name: 'Head, Neck & Shoulder Acupressure (45 mins)',
      nameMm: 'ခေါင်း၊ လည်ပင်း၊ ပခုံး အကြောပြင် (၄၅ မိနစ်)',
      category: 'massage',
      categoryId: 'scat_massage',
      pricingMethod: 'duration_based',
      durationMinutes: 45,
      priceMMK: 20000,
      defaultCommissionRule: { type: 'fixed', value: 6000, ruleId: 'crule_fixed7000', version: 1 },
      commissionRuleId: 'crule_fixed7000',
      isActive: true,
    },
    {
      id: 'srv_6',
      name: 'Natural Herbal Facial Treatment (60 mins)',
      nameMm: 'သဘာဝတိုင်းရင်းဆေး မျက်နှာပေါင်းတင် အလှပြုပြင် (၆၀ မိနစ်)',
      category: 'facial',
      categoryId: 'scat_facial',
      pricingMethod: 'duration_based',
      durationMinutes: 60,
      priceMMK: 28000,
      defaultCommissionRule: { type: 'percentage', value: 35, ruleId: 'crule_pct35', version: 1 },
      commissionRuleId: 'crule_pct35',
      isActive: true,
    },
    {
      id: 'srv_7',
      name: 'VIP KTV Room Karaoke (Per Hour)',
      nameMm: 'VIP ကာရာအိုကေ အခန်းဝန်ဆောင်မှု (၁ နာရီ)',
      category: 'ktv',
      categoryId: 'scat_ktv',
      pricingMethod: 'hourly',
      durationMinutes: 60,
      priceMMK: 35000,
      defaultCommissionRule: { type: 'percentage', value: 20, version: 1 },
      isActive: true,
    },
  ];

  // 6a. Product Categories
  const defaultProductCategories: ProductCategory[] = [
    {
      id: 'pcat_drink',
      code: 'PC-DRINK',
      name: 'Beverages & Beers',
      nameMm: 'ဘီယာနှင့် အဖျော်ယမကာ',
      description: 'Canned beers, spirits and chilled drinks',
      sortOrder: 1,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'pcat_softdrink',
      code: 'PC-SOFT',
      name: 'Soft Drinks & Energy',
      nameMm: 'အချိုရည်နှင့် ရေသန့်',
      description: 'Mineral water, sodas and energy drinks',
      sortOrder: 2,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'pcat_oil',
      code: 'PC-OIL',
      name: 'Spa Oils & Herbal Balms',
      nameMm: 'စပါလိမ်းဆီနှင့် ဆေးဝါး',
      description: 'Massage aromatic oils and takeaway balms',
      sortOrder: 3,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'pcat_food',
      code: 'PC-FOOD',
      name: 'Food & Snacks',
      nameMm: 'အစားအသောက်နှင့် လက်ဖက်ရည်ပွဲ',
      description: 'Fried appetizers, traditional tea salad and nuts',
      sortOrder: 4,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
  ];

  // 6b. Products & Inventory
  const defaultProducts: ProductItem[] = [
    {
      id: 'prd_1',
      name: 'Myanmar Beer Can (330ml)',
      nameMm: 'မြန်မာဘီယာဗူး',
      sku: 'SKU-BEER-01',
      category: 'drink',
      categoryId: 'pcat_drink',
      costPriceMMK: 2400,
      sellingPriceMMK: 3500,
      trackStock: true,
      stockQty: 96,
      unit: 'can',
      unitMm: 'ဗူး',
      isActive: true,
    },
    {
      id: 'prd_2',
      name: 'Heineken Beer Can (330ml)',
      nameMm: 'ဟိုင်းနီးကင်းဘီယာဗူး',
      sku: 'SKU-BEER-02',
      category: 'drink',
      categoryId: 'pcat_drink',
      costPriceMMK: 3200,
      sellingPriceMMK: 4500,
      trackStock: true,
      stockQty: 48,
      unit: 'can',
      unitMm: 'ဗူး',
      isActive: true,
    },
    {
      id: 'prd_3',
      name: 'Red Bull Energy Drink',
      nameMm: 'ရက်ဘူးလ် ခွန်အားဖြည့်အချိုရည်',
      sku: 'SKU-DRK-01',
      category: 'drink',
      categoryId: 'pcat_softdrink',
      costPriceMMK: 1800,
      sellingPriceMMK: 2800,
      trackStock: true,
      stockQty: 72,
      unit: 'can',
      unitMm: 'ဗူး',
      isActive: true,
    },
    {
      id: 'prd_4',
      name: 'Purified Drinking Water 1L',
      nameMm: 'သန့်ရှင်းသော သောက်ရေသန့် (၁ လီတာ)',
      sku: 'SKU-WTR-01',
      category: 'drink',
      categoryId: 'pcat_softdrink',
      costPriceMMK: 600,
      sellingPriceMMK: 1000,
      trackStock: true,
      stockQty: 120,
      unit: 'bottle',
      unitMm: 'ပုလင်း',
      isActive: true,
    },
    {
      id: 'prd_5',
      name: 'Coca Cola Can',
      nameMm: 'ကိုကာကိုလာဗူး',
      sku: 'SKU-DRK-02',
      category: 'drink',
      categoryId: 'pcat_softdrink',
      costPriceMMK: 1200,
      sellingPriceMMK: 2000,
      trackStock: true,
      stockQty: 60,
      unit: 'can',
      unitMm: 'ဗူး',
      isActive: true,
    },
    {
      id: 'prd_6',
      name: 'Herbal Massage Balm & Oil (100ml)',
      nameMm: 'တိုင်းရင်းဆေးလိမ်းဆီနှင့် အကြောပြေလိမ်းဆေး',
      sku: 'SKU-OIL-01',
      category: 'oil_cosmetic',
      categoryId: 'pcat_oil',
      costPriceMMK: 6500,
      sellingPriceMMK: 12000,
      trackStock: true,
      stockQty: 35,
      unit: 'bottle',
      unitMm: 'ဘူး',
      isActive: true,
    },
    {
      id: 'prd_7',
      name: 'Crispy Snack Assortment / Fried Chicken',
      nameMm: 'ကြက်ကြော်နှင့် အကြော်စုံလက်ဖက်ပွဲ',
      sku: 'SKU-SNK-01',
      category: 'food',
      categoryId: 'pcat_food',
      costPriceMMK: 4000,
      sellingPriceMMK: 7000,
      trackStock: true,
      stockQty: 30,
      unit: 'portion',
      unitMm: 'ပွဲ',
      isActive: true,
    },
  ];

  // 7. Customers with sample credit
  const defaultCustomers: Customer[] = [
    {
      id: 'cus_1',
      name: 'Ko Myo Win (ကိုမျိုးဝင်း - VIP)',
      phone: '09-799112233',
      creditAllowed: true,
      creditLimitMMK: 500000,
      currentBalanceMMK: 65000, // owes 65,000 MMK
      notes: 'Regular customer. Settles bill every weekend.',
      status: 'active',
      createdAt: now,
    },
    {
      id: 'cus_2',
      name: 'Daw Nu Nu Hlaing (ဒေါ်နုနုလှိုင်)',
      phone: '09-450123456',
      creditAllowed: true,
      creditLimitMMK: 300000,
      currentBalanceMMK: 0,
      notes: 'Prefers Thai Aromatherapy with Ma Hnin Nu.',
      status: 'active',
      createdAt: now,
    },
    {
      id: 'cus_3',
      name: 'Ko Aung Kyaw (ကိုအောင်ကျော်)',
      phone: '09-261234567',
      creditAllowed: true,
      creditLimitMMK: 200000,
      currentBalanceMMK: 35000,
      notes: 'Company party organizer for KTV.',
      status: 'active',
      createdAt: now,
    },
  ];

  // 8. Payment Methods Master
  const defaultPaymentMethods: PaymentMethodRecord[] = [
    {
      id: 'pm_cash',
      code: 'cash',
      name: 'Cash (MMK)',
      nameMm: 'ငွေသား',
      type: 'cash',
      sortOrder: 1,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'pm_kpay',
      code: 'kpay',
      name: 'KBZPay',
      nameMm: 'ကေဘီဇက်ပလက်',
      type: 'digital_wallet',
      accountName: 'Shwe Thiri Spa Merchant',
      accountNumber: '09798881234',
      sortOrder: 2,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'pm_wave',
      code: 'wave',
      name: 'WavePay',
      nameMm: 'ဝေ့ဗ်မန်းနီး',
      type: 'digital_wallet',
      accountName: 'Shwe Thiri Lounge',
      accountNumber: '09450009876',
      sortOrder: 3,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'pm_cbpay',
      code: 'cbpay',
      name: 'CB Pay',
      nameMm: 'စီဘီပလက်',
      type: 'digital_wallet',
      accountName: 'Shwe Thiri Co., Ltd',
      accountNumber: '0012-3456-7890',
      sortOrder: 4,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'pm_ayapay',
      code: 'ayapay',
      name: 'AYA Pay',
      nameMm: 'ဧရာပလက်',
      type: 'digital_wallet',
      accountName: 'Shwe Thiri Enterprise',
      accountNumber: '09798881234',
      sortOrder: 5,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'pm_credit',
      code: 'credit',
      name: 'Customer Credit / Ledger',
      nameMm: 'ဖောက်သည်ကြွေးကျန်စာရင်း',
      type: 'credit',
      sortOrder: 6,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
  ];

  // 9. Expense Categories Master
  const defaultExpenseCategories: ExpenseCategoryRecord[] = [
    {
      id: 'ecat_fuel',
      code: 'EXP-FUEL',
      name: 'Generator Fuel (Diesel)',
      nameMm: 'မီးစက်ဒီဇယ်ဆီ',
      isDeductible: true,
      sortOrder: 1,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'ecat_laundry',
      code: 'EXP-LAUNDRY',
      name: 'Laundry & Linen Services',
      nameMm: 'ပုဝါ၊ အိပ်ရာခင်း လျှော်ဖွပ်ခ',
      isDeductible: true,
      sortOrder: 2,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'ecat_utilities',
      code: 'EXP-UTIL',
      name: 'Utilities (Electricity, Water, WiFi)',
      nameMm: 'လျှပ်စစ်၊ ရေနှင့် အင်တာနက်ဖိုး',
      isDeductible: true,
      sortOrder: 3,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'ecat_supplies',
      code: 'EXP-SUPPLY',
      name: 'Herbal Oils & Shop Supplies',
      nameMm: 'စပါဆေးဝါးနှင့် ဆိုင်သုံးပစ္စည်းများ',
      isDeductible: true,
      sortOrder: 4,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'ecat_meals',
      code: 'EXP-MEAL',
      name: 'Staff Meal Allowance',
      nameMm: 'ဝန်ထမ်းထမင်းစရိတ်',
      isDeductible: true,
      sortOrder: 5,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'ecat_repairs',
      code: 'EXP-REPAIR',
      name: 'Equipment Maintenance & Repairs',
      nameMm: 'စက်ပစ္စည်း ပြင်ဆင်ထိန်းသိမ်းစရိတ်',
      isDeductible: true,
      sortOrder: 6,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
  ];

  // 10. Commission Rules Master
  const defaultCommissionRules: CommissionRuleRecord[] = [
    {
      id: 'crule_pct35',
      code: 'CR-PCT-35',
      name: 'Standard 35% Service Commission',
      type: 'percentage',
      percentage: 35,
      version: 1,
      description: 'Standard 35% commission allocated to therapist',
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'crule_pct40',
      code: 'CR-PCT-40',
      name: 'VIP Suite 40% Commission',
      type: 'percentage',
      percentage: 40,
      version: 1,
      description: '40% commission for VIP treatments and KTV host',
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'crule_fixed7000',
      code: 'CR-FIX-7000',
      name: 'Fixed 7,000 MMK Per Session',
      type: 'fixed',
      fixedAmountMMK: 7000,
      version: 1,
      description: 'Fixed 7,000 MMK flat fee payout per completed session',
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'crule_pct_plus_bonus',
      code: 'CR-PCT-BONUS',
      name: '25% + 2,000 MMK Fixed Bonus',
      type: 'percentage_plus_fixed',
      percentage: 25,
      fixedBonusMMK: 2000,
      version: 1,
      description: '25% share of service price plus 2,000 MMK bonus allowance',
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
    {
      id: 'crule_tiered',
      code: 'CR-TIERED',
      name: 'Tiered Performance Commission',
      type: 'tiered',
      version: 1,
      tiers: [
        { minAmountMMK: 0, maxAmountMMK: 30000, type: 'percentage', value: 20 },
        { minAmountMMK: 30001, maxAmountMMK: 50000, type: 'percentage', value: 30 },
        { minAmountMMK: 50001, type: 'percentage', value: 40 },
      ],
      description: 'Tiered rate: 20% under 30k, 30% for 30k-50k, 40% over 50k',
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: 'System Seed',
    },
  ];

  // 8. Sample staff ledger history to demonstrate balances & settlements
  const todayDate = now.split('T')[0];
  const sampleStaffLedger: StaffLedgerEntry[] = [
    {
      id: 'led_sample_1',
      staffId: 'stf_1',
      staffName: 'Ma Hnin Nu',
      type: 'commission' as const,
      amountMMK: 10500, // 30,000 * 35%
      direction: 'credit' as const,
      isSettled: false,
      notes: 'Commission for Body Massage 60m',
      date: todayDate,
      createdBy: 'Daw Sandar',
      createdAt: now,
    },
    {
      id: 'led_sample_2',
      staffId: 'stf_1',
      staffName: 'Ma Hnin Nu',
      type: 'bonus' as const,
      amountMMK: 5000,
      direction: 'credit' as const,
      isSettled: false,
      notes: 'Customer Excellent Service Tip',
      date: todayDate,
      createdBy: 'Daw Sandar',
      createdAt: now,
    },
    {
      id: 'led_sample_3',
      staffId: 'stf_2',
      staffName: 'Ma Aye Thandar',
      type: 'commission' as const,
      amountMMK: 15200, // 38,000 * 40%
      direction: 'credit' as const,
      isSettled: false,
      notes: 'Commission for Thai Aroma 60m',
      date: todayDate,
      createdBy: 'Daw Sandar',
      createdAt: now,
    },
    {
      id: 'led_sample_4',
      staffId: 'stf_2',
      staffName: 'Ma Aye Thandar',
      type: 'advance' as const,
      amountMMK: 10000,
      direction: 'debit' as const,
      isSettled: false,
      notes: 'Emergency transport money advance',
      date: todayDate,
      createdBy: 'Daw Sandar',
      createdAt: now,
    },
    {
      id: 'led_sample_5',
      staffId: 'stf_3',
      staffName: 'Ko Than Naing',
      type: 'commission' as const,
      amountMMK: 7000,
      direction: 'credit' as const,
      isSettled: false,
      notes: 'Fixed commission for Acupressure',
      date: todayDate,
      createdBy: 'Daw Sandar',
      createdAt: now,
    },
  ];

  // 9. Sample Expenses
  const sampleExpenses: ExpenseRecord[] = [
    {
      id: 'exp_sample_1',
      category: 'generator_fuel',
      categoryMm: 'မီးစက်ဒီဇယ်ဆီ',
      description: 'Diesel for generator (မီးပျက်၍ မီးစက်မောင်းရန် ဒီဇယ်ဆီဝယ်ယူခြင်း)',
      amountMMK: 45000,
      paymentMethod: 'cash' as const,
      receiptNumber: 'FUEL-0918',
      date: todayDate,
      recordedBy: 'Maung Kyaw',
      createdAt: now,
    },
    {
      id: 'exp_sample_2',
      category: 'laundry_towels',
      categoryMm: 'မျက်နှာသုတ်ပုဝါ လျှော်ဖွပ်ခ',
      description: 'Daily spa towels and bedsheet laundry service (ပုဝါ၊ အိပ်ရာခင်း လျှော်ခ)',
      amountMMK: 25000,
      paymentMethod: 'kpay' as const,
      receiptNumber: 'LAUN-452',
      date: todayDate,
      recordedBy: 'Daw Sandar',
      createdAt: now,
    },
  ];

  // Atomically commit all initial seed data using bulkPut to prevent any ConstraintError
  await db.transaction('rw', [
    db.settings,
    db.users,
    db.rooms,
    db.diningTables,
    db.staff,
    db.staffTypes,
    db.services,
    db.serviceCategories,
    db.products,
    db.productCategories,
    db.customers,
    db.paymentMethods,
    db.expenseCategoriesMaster,
    db.commissionRulesMaster,
    db.staffLedger,
    db.expenses,
  ], async () => {
    await db.settings.put(defaultSettings);
    // Users are created during First-Run Owner Setup (no default credentials seeded)
    await db.rooms.bulkPut(defaultRooms);
    await db.diningTables.bulkPut(defaultTables);
    await db.staffTypes.bulkPut(defaultStaffTypes);
    await db.staff.bulkPut(defaultStaff);
    await db.serviceCategories.bulkPut(defaultServiceCategories);
    await db.services.bulkPut(defaultServices);
    await db.productCategories.bulkPut(defaultProductCategories);
    await db.products.bulkPut(defaultProducts);
    await db.customers.bulkPut(defaultCustomers);
    await db.paymentMethods.bulkPut(defaultPaymentMethods);
    await db.expenseCategoriesMaster.bulkPut(defaultExpenseCategories);
    await db.commissionRulesMaster.bulkPut(defaultCommissionRules);
    await db.staffLedger.bulkPut(sampleStaffLedger);
    await db.expenses.bulkPut(sampleExpenses);
  });

  console.log('Database seeded successfully with authentic Myanmar business records.');
}

export async function seedForceDemoData(): Promise<void> {
  await Promise.all([
    db.users.clear(),
    db.rooms.clear(),
    db.diningTables.clear(),
    db.staff.clear(),
    db.staffTypes.clear(),
    db.services.clear(),
    db.serviceCategories.clear(),
    db.products.clear(),
    db.productCategories.clear(),
    db.sessions.clear(),
    db.invoices.clear(),
    db.customers.clear(),
    db.customerCreditLedger.clear(),
    db.paymentMethods.clear(),
    db.expenseCategoriesMaster.clear(),
    db.commissionRulesMaster.clear(),
    db.staffLedger.clear(),
    db.staffSettlements.clear(),
    db.expenses.clear(),
    db.cashClosings.clear(),
    db.auditLogs.clear(),
    db.settings.clear(),
  ]);
  await seedDatabaseIfEmpty();
}

